image: Visual Studio 2017

platform:
  - x64

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node 12 x64
  - yarn

test_script:
  - yarn run lint

build_script:
  - ps: if($env:appveyor_repo_tag -eq 'True') { yarn run electron:build }
