version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Lint"
          shell: powershell.exe
          command: |
            yarn
            yarn run lint
      - run:
          name: "Build"
          shell: powershell.exe
          command: |
            yarn run electron:build

