version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/

jobs:
  test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Install dependencies"
          shell: powershell.exe
          command: |
            $env:YARN_CACHE_FOLDER = '~/.cache/yarn'
            yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: "Lint"
          shell: powershell.exe
          command: yarn run lint
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - attach_workspace:
        at: .
      - run:
          name: "Build and deploy"
          shell: powershell.exe
          command: yarn run electron:build
