version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  version: 2
  test:
    jobs:
      - test
  test-build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test

jobs:
  test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Install dependencies"
          shell: powershell.exe
          command: |
            yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - C:\Users\circleci\AppData\Local\Yarn\Cache\v6
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: "Lint"
          shell: powershell.exe
          command: yarn run lint
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Build and deploy"
          shell: powershell.exe
          command: yarn run electron:build
